.pragma library

var list = [
    "Ready for another rock star session, %1?",
    "Let's make today count, %1!",
    "Time to crush those goals, %1.",
    "Stay focused, stay driven, %1.",
    "Welcome back, %1. Let's build something great.",
    "Your potential is limitless, %1.",
    "One step closer to your dreams, %1.",
    "Focus is the key to mastery, %1.",
    "Go get 'em, %1!",
    "Discipline equals freedom, %1.",
    "The secret of getting ahead is getting started, %1.",
    "Don't stop until you're proud, %1.",
    "Quality is not an act, it is a habit, %1.",
    "Believe you can and you're halfway there, %1.",
    "Your future is created by what you do today, %1.",
    "Make it work, then make it better, %1.",
    "Codes are written by humans, but mastered by you, %1.",
    "Logic will get you from A to B. Imagination will take you everywhere, %1.",
    "The only way to do great work is to love what you do, %1.",
    "Success is the sum of small efforts, repeated day-in and day-out, %1.",
    "Action is the foundational key to all success, %1.",
    "Focus on being productive instead of busy, %1.",
    "The best way to predict the future is to invent it, %1.",
    "Great things are done by a series of small things brought together, %1.",
    "Efficiency is doing things right; effectiveness is doing the right things, %1.",
    "Stay hungry, stay foolish, %1.",
    "The expert in anything was once a beginner, %1.",
    "Don't wait. The time will never be just right, %1.",
    "Every line of code is a step toward your vision, %1.",
    "Master your environment, master your craft, %1.",
    "Deep work mode: Activated, %1.",
    "Flow state is calling your name, %1.",
    "Leave the world better than you found it, %1.",
    "Consistency beats talent every single time, %1.",
    "You are the architect of your own reality, %1.",
    "Fortune favors the bold, %1.",
    "Your only limit is your mind, %1.",
    "Work hard in silence, let success be your noise, %1.",
    "Success doesn't just find you. You have to go out and get it, %1.",
    "Dream big. Start small. Act now, %1.",
    "Don't count the days, make the days count, %1.",
    "Persistence overrides resistance, %1.",
    "Fuel your passion with focus, %1.",
    "The harder you work for something, the greater you'll feel when you achieve it, %1.",
    "Push yourself, because no one else is going to do it for you, %1.",
    "Greatness lives in the details, %1.",
    "Solve the problem, then write the code, %1.",
    "Simplicity is the soul of efficiency, %1.",
    "Your discipline determines your destiny, %1.",
    "Turn your 'shoulds' into 'musts', %1."
];
