#!/usr/bin/env python3
"""
Generates a per-theme kitty color config (themes/<name>/kitty.conf) for each
theme dir, derived from the theme's `colors` file.

Approach: keep a known-good ANSI palette (Catppuccin Mocha) so syntax
highlighting stays readable, but override background / foreground-accent
slots / cursor / selection / URL with the theme's bg + fg colors so the
terminal visibly takes on each theme's identity.

Idempotent — safe to re-run any time.
"""
from pathlib import Path

THEMES_DIR = Path.home() / ".config/hypr/themes"

# Catppuccin Mocha ANSI base — used as fallback palette for color1..color6.
# Provides nice readable colored text regardless of theme.
ANSI = {
    "color1": "#f38ba8",  "color9":  "#f38ba8",  # red
    "color2": "#a6e3a1",  "color10": "#a6e3a1",  # green
    "color3": "#f9e2af",  "color11": "#f9e2af",  # yellow
    "color4": "#89b4fa",  "color12": "#89b4fa",  # blue
    "color5": "#f5c2e7",  "color13": "#f5c2e7",  # magenta
    "color6": "#94e2d5",  "color14": "#94e2d5",  # cyan
}

# Per-theme override: which ANSI slot should be replaced by the theme accent,
# so commands that print this color (e.g. error messages in a red theme) feel
# extra "on-brand". Optional — themes not listed here keep the full standard
# palette.
ACCENT_SLOT = {
    "red":     "color1",
    "gaming":  "color1",
    "orange":  "color1",  # red-ish family
    "gold":    "color3",
    "green":   "color2",
    "nature":  "color2",
    "teal":    "color6",
    "cyan":    "color6",
    "blue":    "color4",
    "coding":  "color4",
    "purple":  "color5",
    "magenta": "color5",
}


def shade(hex6, factor):
    """Multiply each RGB channel by factor, clamp to 0-255."""
    r = int(hex6[0:2], 16)
    g = int(hex6[2:4], 16)
    b = int(hex6[4:6], 16)
    r = max(0, min(255, int(r * factor)))
    g = max(0, min(255, int(g * factor)))
    b = max(0, min(255, int(b * factor)))
    return f"{r:02x}{g:02x}{b:02x}"


def parse_colors(path):
    out = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if "=" not in line or line.startswith("#"):
                continue
            k, _, v = line.partition("=")
            v = v.strip().strip("'").strip('"')
            out[k.strip()] = v
    return out


def render(theme_name, bg, fg):
    bg_dark = shade(bg, 0.6)
    bg_light = shade(bg, 1.6)
    fg_neutral = "#cdd6f4"   # readable body text
    fg_dim = "#a6adc8"

    lines = [
        f"# Auto-generated by update_kitty_themes.py for theme: {theme_name}",
        f"# Edit the script or the theme's colors file, then re-run; do not edit here.",
        "",
        f"background            #{bg}",
        f"foreground            {fg_neutral}",
        f"cursor                #{fg}",
        f"cursor_text_color     #{bg}",
        f"selection_background  #{fg}",
        f"selection_foreground  #{bg}",
        f"url_color             #{fg}",
        f"active_border_color   #{fg}",
        f"inactive_border_color #{shade(bg, 1.3)}",
        f"active_tab_background #{fg}",
        f"active_tab_foreground #{bg}",
        f"inactive_tab_background #{bg_dark}",
        f"inactive_tab_foreground {fg_dim}",
        "",
        f"# ANSI palette (Catppuccin Mocha base, theme accent boosted)",
        f"color0  #{bg_dark}",
        f"color8  #{bg_light}",
        f"color7  {fg_neutral}",
        f"color15 #ffffff",
    ]
    # Standard ANSI 1-6 + brights
    palette = dict(ANSI)
    # Replace the theme's accent slot (and its bright pair) with the theme's fg
    slot = ACCENT_SLOT.get(theme_name)
    if slot:
        palette[slot] = f"#{fg}"
        # bright pair (color8+N for color N)
        bright = "color" + str(int(slot[5:]) + 8)
        palette[bright] = f"#{fg}"
    for k in sorted(palette, key=lambda s: int(s[5:])):
        lines.append(f"{k:7s} {palette[k]}")
    return "\n".join(lines) + "\n"


def main():
    for theme_dir in sorted(THEMES_DIR.iterdir()):
        if not theme_dir.is_dir():
            continue
        colors_file = theme_dir / "colors"
        if not colors_file.exists():
            print(f"skip {theme_dir.name} (no colors)")
            continue
        c = parse_colors(colors_file)
        bg = c.get("bg_color", "")
        fg = c.get("fg_color", "")
        if not bg or not fg:
            print(f"skip {theme_dir.name} (incomplete colors)")
            continue
        out = theme_dir / "kitty.conf"
        out.write_text(render(theme_dir.name, bg, fg))
        print(f"wrote {out}")


if __name__ == "__main__":
    main()
