# monitors
monitor=,preferred,auto,auto

# programs
$terminal = kitty
$fileManager = thunar
$menu = wofi --show drun

# autostart
exec-once = /home/malek/.config/hypr/scripts/autostart.sh

# environment
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24


env = QT_QPA_PLATFORMTHEME,qt5ct

# look and feel
source = ~/.config/hypr/theme.conf

general {
    gaps_in = 5
    gaps_out = 15
    border_size = 2
    col.active_border = $active_border_col
    col.inactive_border = $inactive_border_col
    layout = dwindle
    resize_on_border = false
    allow_tearing = false
}

decoration {
    rounding = 10
    active_opacity = 0.95
    inactive_opacity = 0.85

    shadow {
        enabled = true
        range = 20
        render_power = 3
        color = $shadow_col
    }

    blur {
        enabled = true
        size = 5
        passes = 3
        new_optimizations = true
        ignore_opacity = true
    }
}

animations {
    enabled = yes
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 5, myBezier
    animation = windowsOut, 1, 5, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}

# input
input {
    kb_layout = us
    follow_mouse = 1
    sensitivity = 0
    touchpad {
        natural_scroll = false
    }
}

# keybindings
source = ~/.config/hypr/keybindings.conf

### Window rules ###
# windowrulev2 = suppressevent maximize, class:.*
##Old: windowrulev2 = float, class:^(kitty)$
# New: windowrule = match:class ^(kitty)$, float, on 

# wofi clipboard
windowrule = match:class ^cliphist$, float 1
windowrule = match:class ^cliphist$, pin 1
windowrule = match:class ^cliphist$, border_size 0

# pavucontrol
windowrule = match:class ^org.pulseaudio.pavucontrol$, float 1
windowrule = match:class ^org.pulseaudio.pavucontrol$, center 1
windowrule = match:class ^org.pulseaudio.pavucontrol$, size 800 600

# blueman-manager
windowrule = match:class ^blueman-manager$, float 1
windowrule = match:class ^blueman-manager$, center 1
windowrule = match:class ^blueman-manager$, size 800 600

# check_in (QML Popup)
windowrule = match:title ^Check-In$, float 1
windowrule = match:title ^Check-In$, center 1
windowrule = match:title ^Check-In$, size 600 350
windowrule = match:title ^Check-In$, animation none
windowrule = match:title ^Check-In$, pin 1

# Session Feedback (QML Popup)
windowrule = match:title ^Session Feedback$, float 1
windowrule = match:title ^Session Feedback$, center 1
windowrule = match:title ^Session Feedback$, size 500 450
windowrule = match:title ^Session Feedback$, animation none
windowrule = match:title ^Session Feedback$, pin 1

# Hypr Package Manager (GTK4)
windowrule = match:class ^com.malek.pkgmgr$, float 1
windowrule = match:class ^com.malek.pkgmgr$, center 1
windowrule = match:class ^com.malek.pkgmgr$, size 1000 700
windowrule = match:class ^com.malek.pkgmgr$, pin 1

# Mouse
# no_hardware_cursors = true 
cursor {
    hide_on_key_press = false
    inactive_timeout = 0
}
env = XCURSOR_SIZE,32
env = HYPRCURSOR_SIZE,32
input {
    touchpad {
        disable_while_typing = false
    }
}

xwayland {
  force_zero_scaling = true
}
