#!/bin/bash
# Renders ~/.config/hypr/hyprlock.conf from a template using the active theme's
# colors and an image from that theme's wallpaper pool. Called by switch_theme.sh.
#
# Args: <theme_name>

set -u

theme="${1:?usage: $0 <theme>}"
theme_dir="$HOME/.config/hypr/themes/$theme"
colors_file="$theme_dir/colors"
out="$HOME/.config/hypr/hyprlock.conf"

if [ ! -f "$colors_file" ]; then
    echo "render_hyprlock: no colors file for $theme" >&2
    exit 1
fi

# shellcheck disable=SC1090
source "$colors_file"   # provides bg_color, fg_color, active_border, inactive_border

# Pick a background image: prefer a random one from images/ (slideshow themes),
# else fall back to wallpaper.png.
bg_img=""
if [ -d "$theme_dir/images" ]; then
    bg_img=$(find "$theme_dir/images" -maxdepth 1 -type f \
             \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' \) \
             -size +30k -printf '%p\n' 2>/dev/null | shuf -n 1)
fi
if [ -z "$bg_img" ] && [ -f "$theme_dir/wallpaper.png" ]; then
    bg_img="$theme_dir/wallpaper.png"
fi

# Convert hex (RRGGBB) → decimal triples for rgb()/rgba()
hex_to_rgb() {
    local h="$1"
    printf '%d, %d, %d' "0x${h:0:2}" "0x${h:2:2}" "0x${h:4:2}"
}

fg_rgb=$(hex_to_rgb "$fg_color")
bg_rgb=$(hex_to_rgb "$bg_color")
# A neutral readable label color (light) for the clock — accent for outlines
label_rgb="220, 220, 220"

cat > "$out" <<EOF
# Auto-generated by render_hyprlock.sh for theme: $theme
# Do not edit by hand; re-run the script (or switch_theme.sh) to regenerate.

general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = true
}

background {
    monitor =
    path = $bg_img
    color = rgba($bg_rgb, 1.0)
    blur_passes = 2
    blur_size = 6
    noise = 0.0117
    contrast = 0.85
    brightness = 0.75
    vibrancy = 0.20
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 240, 56
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.18
    dots_center = true
    dots_rounding = -1
    outer_color = rgb($fg_rgb)
    inner_color = rgba($bg_rgb, 0.85)
    font_color = rgba($label_rgb, 1.0)
    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text = <i>Password…</i>
    hide_input = false
    rounding = 12
    check_color = rgb($fg_rgb)
    fail_color = rgb(204, 34, 34)
    fail_text = <i>\$FAIL (\$ATTEMPTS)</i>
    fail_transition = 300
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false
    position = 0, -40
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "\$TIME"
    color = rgba($label_rgb, 1.0)
    font_size = 96
    font_family = JetBrains Mono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date "+%A, %B %-d"
    color = rgba($fg_rgb, 0.95)
    font_size = 22
    font_family = JetBrains Mono Nerd Font
    position = 0, 20
    halign = center
    valign = center
}
EOF

echo "render_hyprlock: wrote $out (theme=$theme, bg=$(basename "$bg_img"))"
